# Sample names, make sure they are stored in DATADIR with suffix {Samples}_R1.fastq.gz
Samples:
    day4_1m:
    day7_1m:
    day10_1m:
    day14_1m:

# directory where fastq files are stored
DATADIR: /workdir/fw262/ShaoPei/pipeline/testData_small 
# genome reference
GENOMEREF: /workdir/References/Chick/GRCg6a/Gallus_gallus.GRCg6a.dna.toplevel.fa
# gene annotations in GTF format
REFGTF: /workdir/References/Chick/GRCg6a/Gallus_gallus.GRCg6a.96.gtf

# define global variables and cell ID sequence range
GLOBAL:
    allowed_mismatch: 10
    BC_range: # cell barcode
        first: 1
        last: 16
    UMI_range: # molecular ID
        first: 17
        last: 26 # 28 for v3, up to 26 for v2 in 10X genomics

# expected number of cells in each experiment
expectedCells: 5000
# minimum coverage required to be considered in HMM feature definition
MINCOV: 5
CORES: 10 

# required programs
PICARD: scripts/outside_tools/picard.jar
DROPSEQ: scripts/outside_tools/Drop-seq_tools-1.12/
GTFTOGENEPRED: scripts/outside_tools/gtfToGenePred
STAREXEC: scripts/outside_tools/STAR-2.5/bin/Linux_x86_64/STAR
FASTQCEXEC: scripts/outside_tools/fastqc
SingleCellHMM: scripts/SingleCellHMM_2.bash
generate_refFlat_script: scripts/generate_refFlat_script_both.R
Rscript: /programs/bin/R/Rscript
# samtools also required

SAMPWDIR:   sampwdir/
TMPDIR: temp
PIPELINE_MAJOR: results_out
