Samples: # same names i.e. {Samples}_R1.fastq.gz and {Samples}_R2.fastq.gz
    day4_0.25m:
    day7_0.25m:

GENOMEREF: references/Gallus_gallus.GRCg6a.dna.toplevel.fa
REFGTF: references/Gallus_gallus.GRCg6a.96.gtf

SAMPWDIR:   sampwdir # directory where summary information is stored
DATADIR: testData_small # directory where fastq files are stored
    
TMPDIR: temp

PIPELINE_MAJOR: results_out # folder where scRNA-seq expression matrices are going to be stored

GLOBAL:
    allowed_mismatch: 10 # outFilterMismatchNmax parameter for STAR alignment
    BC_range: # barcode range
        first: 1
        last: 16
    UMI_range: # unique molecular identifier range
        first: 17
        last: 28 # 28 for v3, up to 26 for v2

PICARD: /programs/picard-tools-2.1.1/picard.jar
DROPSEQ: /home/fw262/miniconda3/share/dropseq_tools-1.13-0/
GTFTOGENEPRED: /home/fw262/miniconda3/bin/gtfToGenePred # used to convert gtf to reFflat format, not needed if annotation is in reFflat
STAREXEC: /programs/STAR-2.5/bin/Linux_x86_64/STAR
# full path of scripts folder
#FULLSCRIPTPATH: #/local/workdir/fw262/uTARAnalysisTool/HMM-scRNA-seq/testGitHub/scripts

CORES: 2 # how many cores to give for each process, snakemake automatically parallelize process using "snakemake -j {numTotalCores}" 
expectedCells: 5000
MERGEBP: 500
THRESH: 10000000
