Samples: # sample name, pointing to cellranger count output {Samples}_cellranger_count/
    WT_TA_5mo:

# GENOMEREF: /fs/cbsuvlaminck2/workdir/References/Chick/GRCg6a/Gallus_gallus.GRCg6a.dna.toplevel.fa
# REFGTF: /fs/cbsuvlaminck2/workdir/References/Chick/GRCg6a/Gallus_gallus.GRCg6a.96.gtf


CR_REF: #DWM - directory containing cellranger count reference
CR_COUNT_EXEC: /home/dwm269/cellranger-5.0.0/cellranger #executable path for cellranger count


SAMPWDIR:   sampwdir # directory where summary information is stored
DATADIR: /workdir/dwm269/muscle_data/ncRNA/tmp_myo/v4 # directory where fastq files are stored

TMPDIR: tmp

#PIPELINE_MAJOR: results_out # folder where scRNA-seq expression matrices are going to be stored
PIPELINE_MAJOR: /workdir/dwm269/muscle_data/ncRNA/results/allMyo_v4_TAR

PICARD: /home/dwm269/miniconda3/envs/scTAR/share/picard-2.18.29-0 /picard.jar
DROPSEQ: /home/fw262/miniconda3/share/dropseq_tools-2.4.0-0/
GTFTOGENEPRED: /home/fw262/miniconda3/bin/gtfToGenePred # used to convert gtf to reFflat format, not needed if annotation is in reFflat
STAREXEC: /programs/STAR-2.5/bin/Linux_x86_64/STAR
#BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored

# full path of scripts folder
#FULLSCRIPTPATH: #/local/workdir/fw262/uTARAnalysisTool/HMM-scRNA-seq/testGitHub/scripts

CORES: 12 # how many cores to give for each process, snakemake automatically parallelize process using "snakemake -j {numTotalCores}"
expectedCells: 5000
MERGEBP: 500
THRESH: 10000000
